### ISSUE TITLE
Duplicate sensor

### ISSUE THREAD

**Issue by benjamindouma** [pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer#5]
Hi Pippyn,

Great idea about the Groniningen afvalwijzer in homeassitant.
I copied the example config to my configuration.yaml file but i get an error. duplicated mapping key at line 85, column -356:
    sensor:
    ^
Maybe i'm missing something but without the code there are no errors. Do you know what is going wrong here? 

kind regards Ben

**Comment by IcyPalm** [comment]
You probably already have a sensor key in the configuration.yaml

Someting like this:
```

sensor: ### <--------------------
  - platform: mqtt
    temperature
.........
........
light:
  - platform: mqtt
    enz enz
.........
........
 sensor: ### <--------------------
    - platform: groningen_afvalwijzer
      resources:                       # (at least 1 required)
        - restafval
        - papier
      postcode: 1111AA                 # (required)
      streetnumber: 1                  # (required)
```

That is not allowed, please combine both keys to one like this:
```

sensor: 
  - platform: mqtt
     temperature
  - platform: groningen_afvalwijzer
      resources:                       # (at least 1 required)
        - restafval
        - papier
      postcode: 1111AA                 # (required)
      streetnumber: 1                  # (required)
.........
........
light:
  - platform: mqtt
    enz enz
.........
........
    
```

**Comment by pippyn** [comment]
@IcyPalm is right

**Comment by benjamindouma** [comment]
yes. that solved the problem of the sensor. i renamed this sensor to sensor afval: and now it works. The only thing that's not working is that i cannot find the senor anywhere. I thought i coud add a sensor card in lovelace and picked one of the items i put in config. can't find any.

**Comment by pippyn** [comment]
that is not the way to solve this. It needs to be under the `sensor:`, you just can't have 2 `sensor:` entries. Please look at @IcyPalm's response again.

**Comment by IcyPalm** [comment]
Actually @pippyn I think @WasNoPlus888 has used quite a cool feature, named sections:
https://www.home-assistant.io/docs/automation/editor/#updating-your-configuration-to-use-the-editor

It is not really well-knows afaik but works like a charm.

Testing with this code:
```
switch: !include switch.yaml

################################################################################
#########                        Sensors                               #########
################################################################################
sensor: !include_dir_merge_list sensor
sensor afval: 
  - platform: groningen_afvalwijzer
    resources:
      - papier
      - kleding
    postcode: 1234AB
    streetnumber: 999
    dateformat: '%Y-%m-%d'
    dateonly: 1


binary_sensor:
```
Gives me perfectly working config:
![image](https://user-images.githubusercontent.com/2883482/82247526-d2b41880-9946-11ea-9ea5-4cffa6ae619d.png)

@WasNoPlus888 could you have a look at a few things for us please:
1. Look in your logs(via Developer Tools in the sidebar -> Logs) and have a look for  some message about the integration `groningen_afvalwijzer`(other than the: `You are using a custom integration.......`)

2. Have a look in the states(as in my screenshot) and see if anything with `afval` is in there

3. If that does not help you could you please post the exact snippet of your configuration you are using in your yaml
